
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
# from sqlGameBackend.game_constants import questions, hints
from game_constants import questions, hints
from scoreboard import Scoreboard

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets/frame0")

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

game_scoreboard = Scoreboard()

window = Tk()

window.geometry("1200x666")
window.configure(bg = "#5F95FF")


canvas = Canvas(
    window,
    bg = "#5F95FF",
    height = 666,
    width = 1200,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    100.0,
    25.0,
    anchor="nw",
    justify="center",
    text="SQL\nMurder\nMystery",
    fill="#FFFFFF",
    font=("Montserrat Bold", 40 * -1)
)

canvas.create_rectangle(
    400.0,
    0.0,
    1200.0,
    666.0,
    fill="#FFFFFF",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    1090.5,
    73.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#EFEFEF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=1018.0,
    y=25.0,
    width=145.0,
    height=0
)

canvas.create_text(
    1050.0,
    34.0,
    anchor="ne",
    text="Points",
    fill="#5F95FF",
    font=("Montserrat Bold", 14 * -1)
)

canvas.create_text(
    1046.0,
    52.0,
    anchor="nw",
    text="350",
    fill="#5F95FF",
    font=("Montserrat Bold", 48 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=game_scoreboard.level_up,
    relief="flat"
)
button_1.place(
    x=1003.0,
    y=268.0,
    width=175.0,
    height=48.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print(game_scoreboard.level),
    relief="flat"
)
button_2.place(
    x=1003.0,
    y=547.0,
    width=175.0,
    height=90.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=1003.0,
    y=203.0,
    width=175.0,
    height=48.0
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    200.0,
    613.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    200.0,
    342.0,
    image=image_image_2
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    200.0,
    324.5,
    image=entry_image_2
)
entry_2 = Text(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=93.0,
    y=251.0,
    width=214.0,
    height=145.0
)

canvas.create_rectangle(
    433.0,
    25.0,
    986.0,
    316.0,
    fill="#D9D9D9",
    outline="")

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    709.5,
    495.5,
    image=entry_image_3
)
entry_3 = Text(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=433.0,
    y=350.0,
    width=553.0,
    height=289.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=1003.0,
    y=138.0,
    width=175.0,
    height=48.0
)
window.resizable(False, False)
window.mainloop()
